### ISSUE TITLE
Not able to post a plunk

### ISSUE THREAD

**Issue by ishandutta2007** [iliakan/plunk#13]
> projdir$ plunk
> /usr/local/lib/node_modules/plunk/bin/plunk:19
>   let plunkContent = yield* updateDir({
>   ^^^
> 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:139:18)
>     at node.js:974:3

after I remove 'let' keyword I start getting 

> 0c4de9c67ed5:rupeerobotwebsite dutishan$ plunk
> /usr/local/lib/node_modules/plunk/lib/updateDir.js:10
> module.exports = function*({auth, dir, description, tags}) {
>                            ^
> 
> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/usr/local/lib/node_modules/plunk/bin/plunk:3:19)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)

**Comment by iliakan** [comment]
Update your Node.JS
