### ISSUE TITLE
Folder uploading doesn't work in Win 7 x64 Home Premium

### ISSUE THREAD

**Issue by Antiai** [iliakan/plunk#14]
What I do:
1) sign in to plnkr.co via my Github profile
2)  go to http://plnkr.co/edit/ 
3) in chrome devtools console run: document.cookie.match(/plnk_session=(\w+)/)[1] and copy session id
4) create c:\users\username\.plunk_config.json with the content { "auth": { "id": "..." } }
5) in terminal go to folder I want to upload to Plunker
6) in terminal run command "plunk"
7) a few seconds later I get this link http://plnkr.co/edit/undefined?p=preview
http://take.ms/pMbBa
8) those link sends to plunk with import error http://take.ms/beGxL

Hope it will be helpful.
Please let me know if you have any questions. Thanks!

**Comment by iliakan** [comment]
Guess, wrong place for  .plunk_config.json, it should be in your home folder.
