### ISSUE TITLE
Authorized usage doesn't work on Windows.

### ISSUE THREAD

**Issue by dmitrykurmanov** [iliakan/plunk#17]
Hello, Ilia! Thanks for your great work and this repo. So plunk just ignores `.plunk_config.json` and creates anonymous plunk. This is because of `const homeDir = require('home-dir')();` in config.js file.

![plunk_auth](https://cloud.githubusercontent.com/assets/22315929/23795679/e594a55e-05a7-11e7-8837-b950ee1e097a.jpg)

With `__dirname` I have correct path ("D:\sandbox\plunk\.plunk_config.json") and authorized plunk creates and updates.

**Comment by dmitrykurmanov** [comment]
This is because of security. We need to create plunk_config.json outside of our project in home direactory in this case, please see issue above and this repo https://github.com/scottcorgan/home-dir

**Comment by iliakan** [comment]
Wait a moment. You want to replace home-dir by the current dir?

**Comment by dmitrykurmanov** [comment]
@iliakan no, it is ok to use home-dir. I've created this issue for some people who came from "google" with the same problem.

**Comment by iliakan** [comment]
You mean home-dir module doesn't work?

**Comment by dmitrykurmanov** [comment]
@iliakan, I just added .plunk_config.json in my current dir and think that authorized plunk doesn't work. Then I understood idea of home-dir. It is good. And created pull request with info about it. And then I've posted this issue for some people with same problem. May be it was wrong, sorry about confusion :) In fact everything is ok with "plunk" repo.
